#!/bin/sh
# 
# File:   configure.sh
# Author: Javier Marrero
#
# This file belongs to the MEL microkernel, a part of the MuOS project. As such, it is licensed under the GNU-GPL v3.0
# or later.
#
# Created on Jan 12, 2023, 3:05:26 AM
#

# Notice: This is not a GNU-Autotools configure script. It is a custom configuration script that generates the 
# definition header that is used in the MEL kernel to hold conditional compilation macros. Have this in mind when
# modifying this script.

# Default configuration variables
# ===============================
CONFIG_DEBUG=0

# Configuration script code
# ===============================

# Local variables
default=0
hfile="./includes/kernel/config.h"

printf "\033[32mWriting the header to the configuration file '$hfile'.\033[0m\n"

printf "// config.h - This file is auto generated, please, do not modify." > $hfile
printf "// -------- " >> $hfile
printf "//\n// Copyright (C) 2023, J. Marrero.\n// μOS is free software under the terms of the GNU-GPL v3" >> $hfile
printf "//\n//\n" >> $hfile
printf "// This file is automatically generated by the configuration script of μOS. Please, change it in no way.\n" >> $hfile
printf "// If you wish, you may change the default values of configuration and call the configure script with the default\n" >> $hfile
printf "// values. If the configuration script is called normally, one will have to enter all the configuration manually.\n" >> $hfile
printf "// However, to suit your specific needs you may need to perform the process at least once.\n" >> $hfile
printf "// This script is automatically called with its default values by NetBeans when building the project.\n//\n\n" >> $hfile


# Write the variables one by one
printf "#define MEL_KERNEL_CONFIG_DEBUG $CONFIG_DEBUG\n" >> $hfile

# Done
printf "\033[32mdone configuring the kernel...\033[0m\n"
