// config.h - This file is auto generated, please, do not modify.// -------- //
// Copyright (C) 2023, J. Marrero.
// μOS is free software under the terms of the GNU-GPL v3//
//
// This file is automatically generated by the configuration script of μOS. Please, change it in no way.
// If you wish, you may change the default values of configuration and call the configure script with the default
// values. If the configuration script is called normally, one will have to enter all the configuration manually.
// However, to suit your specific needs you may need to perform the process at least once.
// This script is automatically called with its default values by NetBeans when building the project.
//

#define MEL_KERNEL_CONFIG_DEBUG 0
